### ISSUE TITLE
No client connected to Websocket

### ISSUE THREAD

**Issue by calvinirwan** [james-henderson/simple-brepl#9]
I've run (simple-brepl)  and when i execute `(js/alert "Hello World")`, it returns `java.io.IOException: No client connected to Websocket`

my `(brepl-js)` result is `"window.simple_brepl_ip=null;window.simple_brepl_port=null;"` is this normal ?

I don't understand what went wrong, i've done the 5 steps accordingly

**Comment by james-henderson** [comment]
Hi Calvin,

I presume you're running `(brepl-js)` when the browser REPL is not running? If so, this is correct - the client doesn't have a REPL server to connect to. Alternatively, it could be that your page response is caching the result of brepl-js, rather than re-executing it on each request? Could you check what gets sent to your browser when the bREPL is open, after a refresh?

James

**Comment by calvinirwan** [comment]
Nope i run 2 repl, after i ran the brepl, i use the other one to check the `(brepl-js)` and the result still `"window.simple_brepl_ip=null;window.simple_brepl_port=null;"`. I don't see anything sent to my browser after the brepl is open.

when i run the brepl i get this message,
`WARNING: Symbol event/IEventType is not a protocol at line 25 file:/C:/Users/Calvin/.m2/repository/weasel/weasel/0.4.2/weasel-0.4.2.jar!/weasel/impls/websocket.cljs`

perhaps this happened due to my clojurescript version ? i use the 2202 version

**Comment by james-henderson** [comment]
That could well do it - 2202 is quite old and I recall there being some breaking changes in between. Could you try a more recent version?

Cheers,

James

**Comment by calvinirwan** [comment]
upgrading to 2371  and it works fine, thanks

**Comment by james-henderson** [comment]
No worries, glad it's working :)
